steps:
  - name: ':docker: :package:'
    plugins:
      'docker-compose#v1.7.0':
        build: fusion-cli
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - name: ':docker: :package: node8'
    plugins:
      'docker-compose#v1.7.0':
        build: fusion-cli-node-last
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - command: yarn flow
    name: ':flowtype:'
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-cli
    agents:
      queue: workers
  - command: yarn flow
    name: ':flowtype: node8'
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-cli-node-last
    agents:
      queue: workers
  - name: ':eslint:'
    command: yarn lint
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-cli
    agents:
      queue: workers
  - name: ':eslint: node8'
    command: yarn lint
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-cli-node-last
    agents:
      queue: workers
  - name: ':node: :white_check_mark:' worker 0
    command: .buildkite/nodeTests 0
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-cli
    agents:
      queue: workers
  - name: ':node: :white_check_mark: node8' worker 0
    command: .buildkite/nodeTests 0
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-cli-node-last
    agents:
      queue: workers
  - name: ':node: :white_check_mark:' worker 1
    command: .buildkite/nodeTests 1
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-cli
    agents:
      queue: workers
  - name: ':node: :white_check_mark: node8' worker 1
    command: .buildkite/nodeTests 1
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-cli-node-last
    agents:
      queue: workers
  - name: ':node: :white_check_mark:' worker 2
    command: .buildkite/nodeTests 2
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-cli
    agents:
      queue: workers
  - name: ':node: :white_check_mark: node8' worker 2
    command: .buildkite/nodeTests 2
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-cli-node-last
    agents:
      queue: workers
  - name: ':node: :white_check_mark:' worker 3
    command: .buildkite/nodeTests 3
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-cli
    agents:
      queue: workers
  - name: ':node: :white_check_mark: node8' worker 3
    command: .buildkite/nodeTests 3
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-cli-node-last
    agents:
      queue: workers
  - name: ':node: :white_check_mark:' worker 4
    command: .buildkite/nodeTests 4
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-cli
    agents:
      queue: workers
  - name: ':node: :white_check_mark: node8' worker 4
    command: .buildkite/nodeTests 4
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-cli-node-last
    agents:
      queue: workers
